// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0xh83O7dbVdfeLhjgqqjqnaCNr_5MGs0',
    appId: '1:696014027777:web:85db924a08fdf79fb35400',
    messagingSenderId: '696014027777',
    projectId: 'invetory-app-adomz-2026',
    authDomain: 'invetory-app-adomz-2026.firebaseapp.com',
    storageBucket: 'invetory-app-adomz-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQePNUIaS1StuE0NzUk12rUrPHTghZ0yI',
    appId: '1:696014027777:android:3ebfe9f3f39bd6d8b35400',
    messagingSenderId: '696014027777',
    projectId: 'invetory-app-adomz-2026',
    storageBucket: 'invetory-app-adomz-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3TqX5xEYMB8hjaAE61lzHPX6RUWK49tQ',
    appId: '1:696014027777:ios:fbe1ab5f1937f7dcb35400',
    messagingSenderId: '696014027777',
    projectId: 'invetory-app-adomz-2026',
    storageBucket: 'invetory-app-adomz-2026.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3TqX5xEYMB8hjaAE61lzHPX6RUWK49tQ',
    appId: '1:696014027777:ios:fbe1ab5f1937f7dcb35400',
    messagingSenderId: '696014027777',
    projectId: 'invetory-app-adomz-2026',
    storageBucket: 'invetory-app-adomz-2026.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0xh83O7dbVdfeLhjgqqjqnaCNr_5MGs0',
    appId: '1:696014027777:web:69d82235bf9bfdf8b35400',
    messagingSenderId: '696014027777',
    projectId: 'invetory-app-adomz-2026',
    authDomain: 'invetory-app-adomz-2026.firebaseapp.com',
    storageBucket: 'invetory-app-adomz-2026.firebasestorage.app',
  );
}
